a:	inputbuf.o	lexer.o	parser.o
	g++	inputbuf.o	lexer.o	parser.o

inputbuf.o:	inputbuf.cc	inputbuf.h
	g++	-c	inputbuf.cc

lexer.o:	lexer.cc	lexer.h
	g++	-c	lexer.cc

parser.o:	parser.cc	parser.h
	g++	-c	parser.cc